# Generated by Django 5.0 on 2023-12-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
    ]
