# Generated by Django 5.0 on 2023-12-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_usuario_nombre_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(default='sergio', on_delete=django.db.models.deletion.CASCADE, to='database.usuario'),
        ),
    ]
