# Generated by Django 5.0 on 2023-12-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_transaccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(default='hoid', on_delete=django.db.models.deletion.CASCADE, to='database.usuario'),
        ),
    ]
