# Generated by Django 5.0 on 2023-12-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_transaccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
